export const questions = [
  "What’s your current comfort song on repeat?",
  "What’s a tiny thing that instantly improves your mood?",
  "What’s a trend you lowkey enjoy more than you admit?",
  "What’s your go-to way to reset after a long day?",
  "What’s a food you could eat every day and not get bored?",
  "What’s a random skill you wish you had right now?",
  "What’s your current phone wallpaper vibe?",
  "What’s something that always makes you laugh no matter what?",
  "What’s your ideal way to spend a free evening?",
  "What’s a habit you’re proud of building lately?",
  "What’s a color that matches your personality right now?",
  "What’s your comfort YouTube genre?",
  "What’s something small that gives main-character energy?",
  "What’s a song that feels like a warm hug?",
  "What’s your favorite way to procrastinate?",
  "What’s a movie you can rewatch endlessly?",
  "What’s your current sleep schedule aesthetic?",
  "What’s a smell that instantly brings good vibes?",
  "What’s your favorite kind of weather mood?",
  "What’s something you’re oddly good at?",
  "What’s your current obsession, lowkey or highkey?",
  "What’s a simple pleasure you never skip?",
  "What’s your go-to late-night snack?",
  "What’s a word you love the sound of?",
  "What’s your favorite time of day and why?",
  "What’s a tiny win you had recently?",
  "What’s your comfort emoji combo?",
  "What’s a place that feels calm to you?",
  "What’s a show you wish you could watch again for the first time?",
  "What’s your current aesthetic in one word?",
  "What’s a hobby you want to pick up someday?",
  "What’s your favorite way to celebrate small wins?",
  "What’s something that instantly gives you the ick?",
  "What’s a trend you’re tired of seeing?",
  "What’s your favorite chill activity?",
  "What’s your ideal weekend vibe?",
  "What’s a song that matches your energy today?",
  "What’s your favorite type of meme?",
  "What’s something you always overthink?",
  "What’s a routine that keeps you grounded?",
  "What’s your favorite comfort drink?",
  "What’s a random fact you find interesting?",
  "What’s your favorite way to relax your mind?",
  "What’s a food combo that just works?",
  "What’s your current favorite app to scroll?",
  "What’s a sound that instantly relaxes you?",
  "What’s your favorite kind of late-night conversation?",
  "What’s something that feels underrated to you?",
  "What’s your favorite way to start the day?",
  "What’s a quote that lowkey sticks with you?",
  "What’s your favorite casual outfit vibe?",
  "What’s a movie scene you think about often?",
  "What’s your comfort dessert?",
  "What’s a small habit that changed your life a bit?",
  "What’s your favorite season aesthetic?",
  "What’s a song that makes you feel unstoppable?",
  "What’s your current background noise of choice?",
  "What’s something you find oddly satisfying?",
  "What’s your favorite way to unwind before sleep?",
  "What’s a place you want to visit just for the vibes?",
  "What’s your favorite casual conversation topic?",
  "What’s a trend you secretly hope comes back?",
  "What’s your go-to feel-good content?",
  "What’s a food you associate with good memories?",
  "What’s your favorite way to pass time when bored?",
  "What’s something that always makes a day better?",
  "What’s your favorite kind of compliment to receive?",
  "What’s a song that feels nostalgic for you?",
  "What’s your favorite low-effort meal?",
  "What’s a hobby that relaxes you instantly?",
  "What’s your current favorite emoji?",
  "What’s something you enjoy doing alone?",
  "What’s your favorite background music vibe?",
  "What’s a smell that reminds you of home?",
  "What’s your favorite cozy activity?",
  "What’s something you look forward to every week?",
  "What’s your favorite casual snack?",
  "What’s a show you keep recommending to people?",
  "What’s your favorite way to romanticize life?",
  "What’s a tiny thing that boosts your confidence?",
  "What’s your favorite time to be awake?",
  "What’s a song lyric you love right now?",
  "What’s your comfort scroll topic?",
  "What’s a habit you want to build next?",
  "What’s your favorite kind of daydream?",
  "What’s something that gives peaceful energy?",
  "What’s your favorite chill playlist vibe?",
  "What’s a movie that feels like a comfort blanket?",
  "What’s your go-to productivity trick?",
  "What’s a food you associate with late nights?",
  "What’s your favorite way to clear your head?",
  "What’s a simple routine you enjoy?",
  "What’s your favorite way to treat yourself?",
  "What’s something that feels very “you”?",
  "What’s your favorite ambient sound?",
  "What’s a show you watch when you don’t want to think?",
  "What’s your favorite casual hobby?",
  "What’s a song that matches rainy weather perfectly?",
  "What’s your favorite way to recharge socially?",
  "What’s a trend you actually like?",
  "What’s your comfort outfit?",
  "What’s something you enjoy learning about?",
  "What’s your favorite lazy-day activity?",
  "What’s a place you feel most yourself?",
  "What’s your favorite way to spend time online?",
  "What’s a small joy you noticed today?",
  "What’s your favorite vibe for nights?",
  "What’s a movie genre you always enjoy?",
  "What’s your favorite casual breakfast?",
  "What’s something that makes you feel calm instantly?",
  "What’s your favorite kind of background show?",
  "What’s a habit that keeps you balanced?",
  "What’s your favorite kind of compliment to give?",
  "What’s a song you discovered recently and loved?",
  "What’s your favorite way to enjoy silence?",
  "What’s a routine you can’t skip?",
  "What’s your favorite kind of creative outlet?",
  "What’s something you enjoy more as you get older?",
  "What’s your favorite way to spend a slow day?",
  "What’s a show you rewatch for comfort?",
  "What’s your favorite low-energy activity?",
  "What’s a song that feels like sunshine?",
  "What’s your favorite way to stay organized?",
  "What’s something you appreciate more now?",
  "What’s your favorite casual hangout vibe?",
  "What’s a sound that gives cozy energy?",
  "What’s your favorite thing about evenings?",
  "What’s a food that feels like a reward?",
  "What’s your favorite way to unwind on weekends?",
  "What’s something that makes you smile without trying?",
  "What’s your favorite kind of playlist?",
  "What’s a habit that makes life easier?",
  "What’s your favorite chill content creator genre?",
  "What’s something that feels comforting to you?",
  "What’s your favorite way to romanticize everyday life?",
  "What’s a song you play when you need motivation?",
  "What’s your favorite lowkey activity?",
  "What’s a smell that feels nostalgic?",
  "What’s your favorite thing to do when it’s quiet?",
  "What’s a routine that feels cozy?",
  "What’s your favorite way to enjoy your own company?",
  "What’s a movie that matches your vibe?",
  "What’s your favorite way to slow down?",
  "What’s something you’re grateful for today?",
  "What’s your favorite kind of background noise?",
  "What’s a habit you want to keep forever?",
  "What’s your favorite way to relax your body?",
  "What’s a song that feels peaceful?",
  "What’s your favorite kind of self-care?",
  "What’s something that feels like a soft reset?",
  "What’s your favorite way to end the day?",
  "What’s a simple thing you love doing?",
  "What’s your favorite cozy vibe?",
  "What’s something that always feels familiar?",
  "What’s your favorite way to enjoy music?",
  "What’s a habit that helps you feel present?",
  "What’s your favorite kind of calm moment?",
  "What’s a small habit that improves your mornings?",
  "What’s your favorite background activity while working?",
  "What’s something that makes you feel refreshed?",
  "What’s your favorite way to enjoy weekends alone?",
  "What’s a song you associate with good weather?",
  "What’s your favorite cozy corner activity?",
  "What’s something that feels like home energy?",
  "What’s your favorite way to disconnect for a bit?",
  "What’s a simple routine that makes days smoother?",
  "What’s your favorite way to boost your mood quickly?",
  "What’s a sound that feels grounding?",
  "What’s your favorite chill evening plan?",
  "What’s something that feels effortlessly fun?",
  "What’s your favorite way to enjoy a quiet morning?",
  "What’s a song that matches sunset vibes?",
  "What’s your favorite low-pressure hobby?",
  "What’s something you find calming to watch?",
  "What’s your favorite way to reset mentally?",
  "What’s a routine that feels like self-care?",
  "What’s your favorite background vibe for studying or working?",
  "What’s something that makes a space feel cozy?",
  "What’s your favorite way to enjoy downtime?",
  "What’s a song that makes you feel lighter?",
  "What’s your favorite kind of slow moment?",
  "What’s something you appreciate during quiet nights?",
  "What’s your favorite way to romanticize small moments?",
  "What’s a habit that keeps your energy balanced?",
  "What’s your favorite calm activity before bed?",
  "What’s something that makes evenings feel complete?",
  "What’s your favorite way to enjoy a chill day out?",
  "What’s a smell that instantly relaxes you?",
  "What’s your favorite way to enjoy background music?",
  "What’s something that feels comforting without effort?",
  "What’s your favorite way to recharge emotionally?",
  "What’s a routine that helps you slow life down?",
  "What’s your favorite kind of peaceful content?",
  "What’s something that makes a normal day feel special?",
  "What’s your favorite way to enjoy being offline?",
  "What’s a song that feels like deep breathing?",
  "What’s your favorite calm-night vibe?",
  "What’s something you enjoy noticing in everyday life?",
  "What’s your favorite way to feel present in the moment?",
  "What’s a simple thing that brings you peace?"
];
